// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmTZnUO6FUKMd7rYfDL1JoNhe8PbwT9CY',
    appId: '1:501601556646:web:71fbc11bf2c519edc0fc67',
    messagingSenderId: '501601556646',
    projectId: 'ielts-support-listening',
    authDomain: 'ielts-support-listening.firebaseapp.com',
    databaseURL: 'https://ielts-support-listening-default-rtdb.firebaseio.com',
    storageBucket: 'ielts-support-listening.appspot.com',
    measurementId: 'G-77XCB7F52S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENQ4n9gQ_aS6EHakNk6pEpR0RgFDLyOY',
    appId: '1:501601556646:android:8eb6a6d36e24113bc0fc67',
    messagingSenderId: '501601556646',
    projectId: 'ielts-support-listening',
    databaseURL: 'https://ielts-support-listening-default-rtdb.firebaseio.com',
    storageBucket: 'ielts-support-listening.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASiszVJzShclbDLMdXFzG3QPhV5TENIY8',
    appId: '1:501601556646:ios:e71b6bf535c7db95c0fc67',
    messagingSenderId: '501601556646',
    projectId: 'ielts-support-listening',
    databaseURL: 'https://ielts-support-listening-default-rtdb.firebaseio.com',
    storageBucket: 'ielts-support-listening.appspot.com',
    iosBundleId: 'com.example.miniMinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASiszVJzShclbDLMdXFzG3QPhV5TENIY8',
    appId: '1:501601556646:ios:e71b6bf535c7db95c0fc67',
    messagingSenderId: '501601556646',
    projectId: 'ielts-support-listening',
    databaseURL: 'https://ielts-support-listening-default-rtdb.firebaseio.com',
    storageBucket: 'ielts-support-listening.appspot.com',
    iosBundleId: 'com.example.miniMinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmTZnUO6FUKMd7rYfDL1JoNhe8PbwT9CY',
    appId: '1:501601556646:web:d78ce91f2185c86fc0fc67',
    messagingSenderId: '501601556646',
    projectId: 'ielts-support-listening',
    authDomain: 'ielts-support-listening.firebaseapp.com',
    databaseURL: 'https://ielts-support-listening-default-rtdb.firebaseio.com',
    storageBucket: 'ielts-support-listening.appspot.com',
    measurementId: 'G-P74WSVVS1Y',
  );
}
